### ISSUE TITLE
Request for more startup flags

### ISSUE THREAD

**Issue by mdcryptonfts** [eosswedenorg/thalos#32]
Hey, I noticed you guys added some new flags in the latest versions:

 -c, --config=file  Config file to read [./config.yml]
 -h, --help         display this help text
 -L, --level=value  Log level to use [info]
 -l, --log=file     Path to log file
 -n                 Force the application to take start block from config/api
 -p, --pid=file     Where to write process id
 -v, --version      display the version

When building an indexer on top of Thalos (think something like AA/Hyperion), it would be really great if you could backfill and stream current data simultaneously, which ideally would involve a simple script using flags that are already in the config.yml

For example, let's say my indexer is already running and streaming live data. Without interrupting that process, I'd like to be able to start up another process that launches a second instance of Thalos.

./index-missed-blocks.sh --start_block=1234 --stop_block=5678

This way a service can remain running while also requesting old data. This should be doable at the ship reader level, so it's just a question of being able to spin up a second instance of Thalos and request a specific range of blocks.

Let me know if this makes sense. Thanks.

**Comment by pnx** [comment]
Thanks for the input! I will look into this, I think it is perfectly fine to run multiple instances. It is probably easiest to just spin up another instance as another way would be to implement some sort for simple api to tell the running instance to fetch those blocks.

I think we can start with cli flags because its easier to implement and useful even for other cases than reindexing.

**Comment by pnx** [comment]
fixed in 1.1.0-rc1
